### ISSUE TITLE
Plugin could not be enabled

### ISSUE THREAD

**Issue by Peskdt** [LucasitoInDev/crowty-anti-sign-edit#1]
[07:40:01 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/crowty-anti-sign-edit-1.0-SNAPSHOT.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/crowty-anti-sign-edit-1.0-SNAPSHOT.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[paper-1.20.2.jar:git-Paper-318]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.Main.main(Main.java:134) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.Main.main(Main.java:325) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: org.bukkit.plugin.InvalidDescriptionException: Restricted name, cannot use 0x20 (space character) in a plugin name.
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:27) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[paper-1.20.2.jar:git-Paper-318]
        ... 20 more
        
   
Running on paper 1.20.2

**Comment by LucasitoInDev** [comment]
Problem solved, **apparently I made a mistake with the migration of commands** from another base very different from the current one used...

**Download the latest version now!** - [Download](https://github.com/LucasitoInDev/crowty-anti-sign-edit/releases/tag/1.0-SNAPSHOT)

Thanks for your report ♥
